apiVersion: v1
kind: Pod
metadata:
  name: unittestcarts-db-replicasmod1-pod
spec:
  containers:
  - name: unittestcarts-db-replicasmod1-pod-container
    image: chaos-eater/k8sapi:1.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash", "-c"]
    args: ["python /chaos-eater/sandbox/cycle_20241127_043136/hypothesis/unittest_carts-db-replicas_mod1.py --duration 5"]
    volumeMounts:
      - name: pvc-volume
        mountPath: /chaos-eater
  restartPolicy: Never
  volumes:
    - name: pvc-volume
      persistentVolumeClaim:
        claimName: pvc