FROM docker:27.5.1-dind

RUN echo "Building docker in docker image"
ENV INSIDE_DOCKER=true

#------------------------
# install basic packages
#------------------------
RUN apk add bash
RUN apk add curl
# for envsubst in create_kind_cluster.sh
RUN apk add gettext 

#---------------------
# install environment
#---------------------
WORKDIR /app
COPY . .
RUN chmod +x create_environment.sh
RUN ./create_environment.sh