# Dockerfile
FROM node:18-alpine

WORKDIR /app

# install dependencies based on package.json
COPY ../chaos_eater/frontend ./
RUN npm install

# port settings
EXPOSE 3000

# environment settings
ENV DISABLE_ESLINT_PLUGIN=true
ENV SKIP_PREFLIGHT_CHECK=true

# launch the server
CMD ["npm", "start"]